package com.jmf.impl.dao;

import java.util.List;

import com.jmf.impl.entity.JmfJvmList;

public interface JmfJvmListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_JVM_LIST
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String jvmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_JVM_LIST
     *
     * @mbg.generated
     */
    int insert(JmfJvmList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_JVM_LIST
     *
     * @mbg.generated
     */
    JmfJvmList selectByPrimaryKey(String jvmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_JVM_LIST
     *
     * @mbg.generated
     */
    List<JmfJvmList> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_JVM_LIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JmfJvmList record);
}