package com.jmf.impl.dao;

import java.util.List;

import com.jmf.impl.entity.JmfRecvMsg;

public interface JmfRecvMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_RECV_MSG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String msgSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_RECV_MSG
     *
     * @mbg.generated
     */
    int insert(JmfRecvMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_RECV_MSG
     *
     * @mbg.generated
     */
    JmfRecvMsg selectByPrimaryKey(String msgSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_RECV_MSG
     *
     * @mbg.generated
     */
    List<JmfRecvMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_RECV_MSG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JmfRecvMsg record);
}