package com.jmf.impl.dao;

import java.util.List;

import com.jmf.impl.entity.JmfSendMsg;

public interface JmfSendMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_SEND_MSG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String msgSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_SEND_MSG
     *
     * @mbg.generated
     */
    int insert(JmfSendMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_SEND_MSG
     *
     * @mbg.generated
     */
    JmfSendMsg selectByPrimaryKey(String msgSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_SEND_MSG
     *
     * @mbg.generated
     */
    List<JmfSendMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_SEND_MSG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JmfSendMsg record);
}