package com.jmf.impl.dao;

import java.util.List;

import com.jmf.impl.entity.JmfTaskCertRef;

public interface JmfTaskCertRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CERT_REF
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CERT_REF
     *
     * @mbg.generated
     */
    int insert(JmfTaskCertRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CERT_REF
     *
     * @mbg.generated
     */
    JmfTaskCertRef selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CERT_REF
     *
     * @mbg.generated
     */
    List<JmfTaskCertRef> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CERT_REF
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JmfTaskCertRef record);
}