package com.jmf.impl.dao;

import java.util.List;

import com.jmf.impl.entity.JmfTaskConfig;

public interface JmfTaskConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String taskConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG
     *
     * @mbg.generated
     */
    int insert(JmfTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG
     *
     * @mbg.generated
     */
    JmfTaskConfig selectByPrimaryKey(String taskConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG
     *
     * @mbg.generated
     */
    List<JmfTaskConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JmfTaskConfig record);
}