package com.jmf.impl.dao;

import java.math.BigDecimal;
import java.util.List;

import com.jmf.impl.entity.JmfTest;

public interface JmfTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TEST
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal seqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TEST
     *
     * @mbg.generated
     */
    int insert(JmfTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TEST
     *
     * @mbg.generated
     */
    JmfTest selectByPrimaryKey(BigDecimal seqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TEST
     *
     * @mbg.generated
     */
    List<JmfTest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TEST
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JmfTest record);
}