package com.jmf.impl.dao;

import java.util.List;

import com.jmf.impl.entity.JmfTaskList;

public interface JmfTaskListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_LIST
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_LIST
     *
     * @mbg.generated
     */
    int insert(JmfTaskList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_LIST
     *
     * @mbg.generated
     */
    JmfTaskList selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_LIST
     *
     * @mbg.generated
     */
    List<JmfTaskList> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_LIST
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JmfTaskList record);

    List<JmfTaskList> selectByJvmId(String jvmId);
}