package com.jmf.impl.dao;

import java.util.List;

import com.jmf.impl.entity.JmfTaskConfigHistory;

public interface JmfTaskConfigHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG_HISTORY
     *
     * @mbg.generated
     */
    int insert(JmfTaskConfigHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG_HISTORY
     *
     * @mbg.generated
     */
    List<JmfTaskConfigHistory> selectAll();
}