package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfConfigCert implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.CONFIG_ID
     *
     * @mbg.generated
     */
    private String configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.CERT_SEQ_NO
     *
     * @mbg.generated
     */
    private String certSeqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.CERTIFICATE
     *
     * @mbg.generated
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.NOTE
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.LAST_DATE
     *
     * @mbg.generated
     */
    private Date lastDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.CERT_SENDER
     *
     * @mbg.generated
     */
    private String certSender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_CERT.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_CONFIG_CERT
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.CONFIG_ID
     *
     * @return the value of JMF_CONFIG_CERT.CONFIG_ID
     * @mbg.generated
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.CONFIG_ID
     *
     * @param configId the value for JMF_CONFIG_CERT.CONFIG_ID
     * @mbg.generated
     */
    public void setConfigId(String configId) {
        this.configId = configId == null ? null : configId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.CERT_SEQ_NO
     *
     * @return the value of JMF_CONFIG_CERT.CERT_SEQ_NO
     * @mbg.generated
     */
    public String getCertSeqNo() {
        return certSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.CERT_SEQ_NO
     *
     * @param certSeqNo the value for JMF_CONFIG_CERT.CERT_SEQ_NO
     * @mbg.generated
     */
    public void setCertSeqNo(String certSeqNo) {
        this.certSeqNo = certSeqNo == null ? null : certSeqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.CERTIFICATE
     *
     * @return the value of JMF_CONFIG_CERT.CERTIFICATE
     * @mbg.generated
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.CERTIFICATE
     *
     * @param certificate the value for JMF_CONFIG_CERT.CERTIFICATE
     * @mbg.generated
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate == null ? null : certificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.NOTE
     *
     * @return the value of JMF_CONFIG_CERT.NOTE
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.NOTE
     *
     * @param note the value for JMF_CONFIG_CERT.NOTE
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.LAST_DATE
     *
     * @return the value of JMF_CONFIG_CERT.LAST_DATE
     * @mbg.generated
     */
    public Date getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.LAST_DATE
     *
     * @param lastDate the value for JMF_CONFIG_CERT.LAST_DATE
     * @mbg.generated
     */
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.CERT_SENDER
     *
     * @return the value of JMF_CONFIG_CERT.CERT_SENDER
     * @mbg.generated
     */
    public String getCertSender() {
        return certSender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.CERT_SENDER
     *
     * @param certSender the value for JMF_CONFIG_CERT.CERT_SENDER
     * @mbg.generated
     */
    public void setCertSender(String certSender) {
        this.certSender = certSender == null ? null : certSender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.CREATETIME
     *
     * @return the value of JMF_CONFIG_CERT.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.CREATETIME
     *
     * @param createtime the value for JMF_CONFIG_CERT.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_CERT.UPDATETIME
     *
     * @return the value of JMF_CONFIG_CERT.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_CERT.UPDATETIME
     *
     * @param updatetime the value for JMF_CONFIG_CERT.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_CONFIG_CERT
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", configId=").append(configId);
        sb.append(", certSeqNo=").append(certSeqNo);
        sb.append(", certificate=").append(certificate);
        sb.append(", note=").append(note);
        sb.append(", lastDate=").append(lastDate);
        sb.append(", certSender=").append(certSender);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}