package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.JMF_CONFIG_ID
     *
     * @mbg.generated
     */
    private String jmfConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.APP_NAME
     *
     * @mbg.generated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.KEY
     *
     * @mbg.generated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.VALUE
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.CONFIG_TYPE
     *
     * @mbg.generated
     */
    private String configType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_CONFIG
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.JMF_CONFIG_ID
     *
     * @return the value of JMF_CONFIG.JMF_CONFIG_ID
     * @mbg.generated
     */
    public String getJmfConfigId() {
        return jmfConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.JMF_CONFIG_ID
     *
     * @param jmfConfigId the value for JMF_CONFIG.JMF_CONFIG_ID
     * @mbg.generated
     */
    public void setJmfConfigId(String jmfConfigId) {
        this.jmfConfigId = jmfConfigId == null ? null : jmfConfigId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.APP_NAME
     *
     * @return the value of JMF_CONFIG.APP_NAME
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.APP_NAME
     *
     * @param appName the value for JMF_CONFIG.APP_NAME
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.KEY
     *
     * @return the value of JMF_CONFIG.KEY
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.KEY
     *
     * @param key the value for JMF_CONFIG.KEY
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.VALUE
     *
     * @return the value of JMF_CONFIG.VALUE
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.VALUE
     *
     * @param value the value for JMF_CONFIG.VALUE
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.CONFIG_TYPE
     *
     * @return the value of JMF_CONFIG.CONFIG_TYPE
     * @mbg.generated
     */
    public String getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.CONFIG_TYPE
     *
     * @param configType the value for JMF_CONFIG.CONFIG_TYPE
     * @mbg.generated
     */
    public void setConfigType(String configType) {
        this.configType = configType == null ? null : configType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.DESCRIPTION
     *
     * @return the value of JMF_CONFIG.DESCRIPTION
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.DESCRIPTION
     *
     * @param description the value for JMF_CONFIG.DESCRIPTION
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.CREATETIME
     *
     * @return the value of JMF_CONFIG.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.CREATETIME
     *
     * @param createtime the value for JMF_CONFIG.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG.UPDATETIME
     *
     * @return the value of JMF_CONFIG.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG.UPDATETIME
     *
     * @param updatetime the value for JMF_CONFIG.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_CONFIG
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jmfConfigId=").append(jmfConfigId);
        sb.append(", appName=").append(appName);
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", configType=").append(configType);
        sb.append(", description=").append(description);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}