package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfConfigQmgr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.QM_ID
     *
     * @mbg.generated
     */
    private String qmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.HOST
     *
     * @mbg.generated
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.PORT
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.QUEUE_MANAGER
     *
     * @mbg.generated
     */
    private String queueManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.CHANNEL
     *
     * @mbg.generated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.CCSID
     *
     * @mbg.generated
     */
    private String ccsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.NOTE
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_CONFIG_QMGR.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_CONFIG_QMGR
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.QM_ID
     *
     * @return the value of JMF_CONFIG_QMGR.QM_ID
     * @mbg.generated
     */
    public String getQmId() {
        return qmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.QM_ID
     *
     * @param qmId the value for JMF_CONFIG_QMGR.QM_ID
     * @mbg.generated
     */
    public void setQmId(String qmId) {
        this.qmId = qmId == null ? null : qmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.HOST
     *
     * @return the value of JMF_CONFIG_QMGR.HOST
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.HOST
     *
     * @param host the value for JMF_CONFIG_QMGR.HOST
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.PORT
     *
     * @return the value of JMF_CONFIG_QMGR.PORT
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.PORT
     *
     * @param port the value for JMF_CONFIG_QMGR.PORT
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.QUEUE_MANAGER
     *
     * @return the value of JMF_CONFIG_QMGR.QUEUE_MANAGER
     * @mbg.generated
     */
    public String getQueueManager() {
        return queueManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.QUEUE_MANAGER
     *
     * @param queueManager the value for JMF_CONFIG_QMGR.QUEUE_MANAGER
     * @mbg.generated
     */
    public void setQueueManager(String queueManager) {
        this.queueManager = queueManager == null ? null : queueManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.CHANNEL
     *
     * @return the value of JMF_CONFIG_QMGR.CHANNEL
     * @mbg.generated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.CHANNEL
     *
     * @param channel the value for JMF_CONFIG_QMGR.CHANNEL
     * @mbg.generated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.CCSID
     *
     * @return the value of JMF_CONFIG_QMGR.CCSID
     * @mbg.generated
     */
    public String getCcsid() {
        return ccsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.CCSID
     *
     * @param ccsid the value for JMF_CONFIG_QMGR.CCSID
     * @mbg.generated
     */
    public void setCcsid(String ccsid) {
        this.ccsid = ccsid == null ? null : ccsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.NOTE
     *
     * @return the value of JMF_CONFIG_QMGR.NOTE
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.NOTE
     *
     * @param note the value for JMF_CONFIG_QMGR.NOTE
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.CREATETIME
     *
     * @return the value of JMF_CONFIG_QMGR.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.CREATETIME
     *
     * @param createtime the value for JMF_CONFIG_QMGR.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_CONFIG_QMGR.UPDATETIME
     *
     * @return the value of JMF_CONFIG_QMGR.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_CONFIG_QMGR.UPDATETIME
     *
     * @param updatetime the value for JMF_CONFIG_QMGR.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_CONFIG_QMGR
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qmId=").append(qmId);
        sb.append(", host=").append(host);
        sb.append(", port=").append(port);
        sb.append(", queueManager=").append(queueManager);
        sb.append(", channel=").append(channel);
        sb.append(", ccsid=").append(ccsid);
        sb.append(", note=").append(note);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}