package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfJvmList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_JVM_LIST.JVM_ID
     *
     * @mbg.generated
     */
    private String jvmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_JVM_LIST.IP
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_JVM_LIST.PORT
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_JVM_LIST.NOTE
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_JVM_LIST.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_JVM_LIST.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_JVM_LIST
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_JVM_LIST.JVM_ID
     *
     * @return the value of JMF_JVM_LIST.JVM_ID
     * @mbg.generated
     */
    public String getJvmId() {
        return jvmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_JVM_LIST.JVM_ID
     *
     * @param jvmId the value for JMF_JVM_LIST.JVM_ID
     * @mbg.generated
     */
    public void setJvmId(String jvmId) {
        this.jvmId = jvmId == null ? null : jvmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_JVM_LIST.IP
     *
     * @return the value of JMF_JVM_LIST.IP
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_JVM_LIST.IP
     *
     * @param ip the value for JMF_JVM_LIST.IP
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_JVM_LIST.PORT
     *
     * @return the value of JMF_JVM_LIST.PORT
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_JVM_LIST.PORT
     *
     * @param port the value for JMF_JVM_LIST.PORT
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_JVM_LIST.NOTE
     *
     * @return the value of JMF_JVM_LIST.NOTE
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_JVM_LIST.NOTE
     *
     * @param note the value for JMF_JVM_LIST.NOTE
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_JVM_LIST.CREATETIME
     *
     * @return the value of JMF_JVM_LIST.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_JVM_LIST.CREATETIME
     *
     * @param createtime the value for JMF_JVM_LIST.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_JVM_LIST.UPDATETIME
     *
     * @return the value of JMF_JVM_LIST.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_JVM_LIST.UPDATETIME
     *
     * @param updatetime the value for JMF_JVM_LIST.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_JVM_LIST
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jvmId=").append(jvmId);
        sb.append(", ip=").append(ip);
        sb.append(", port=").append(port);
        sb.append(", note=").append(note);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}