package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfRecvMsg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.MSG_SEQ_NO
     *
     * @mbg.generated
     */
    private String msgSeqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.VERSION
     *
     * @mbg.generated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.TASK_NAME
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.SYS_NAME
     *
     * @mbg.generated
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.MESSAGE_ID
     *
     * @mbg.generated
     */
    private String messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.FILE_NAME
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.MESSAGE_TYPE
     *
     * @mbg.generated
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.SENDER_ID
     *
     * @mbg.generated
     */
    private String senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.RECEIVER_ID
     *
     * @mbg.generated
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.SEND_TIME
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.EXCEPTION_TYPE
     *
     * @mbg.generated
     */
    private String exceptionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.ID_NAME1
     *
     * @mbg.generated
     */
    private String idName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.ID1
     *
     * @mbg.generated
     */
    private String id1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.ID_NAME2
     *
     * @mbg.generated
     */
    private String idName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.ID2
     *
     * @mbg.generated
     */
    private String id2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.ID_NAME3
     *
     * @mbg.generated
     */
    private String idName3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.ID3
     *
     * @mbg.generated
     */
    private String id3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.INFO_NAME1
     *
     * @mbg.generated
     */
    private String infoName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.INFO1
     *
     * @mbg.generated
     */
    private String info1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.INFO_NAME2
     *
     * @mbg.generated
     */
    private String infoName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.INFO2
     *
     * @mbg.generated
     */
    private String info2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.INFO_NAME3
     *
     * @mbg.generated
     */
    private String infoName3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.INFO3
     *
     * @mbg.generated
     */
    private String info3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.INFO_STATUS
     *
     * @mbg.generated
     */
    private String infoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.FILE_PATH
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.ADD_TIME
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.NOTES
     *
     * @mbg.generated
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_RECV_MSG.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_RECV_MSG
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.MSG_SEQ_NO
     *
     * @return the value of JMF_RECV_MSG.MSG_SEQ_NO
     * @mbg.generated
     */
    public String getMsgSeqNo() {
        return msgSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.MSG_SEQ_NO
     *
     * @param msgSeqNo the value for JMF_RECV_MSG.MSG_SEQ_NO
     * @mbg.generated
     */
    public void setMsgSeqNo(String msgSeqNo) {
        this.msgSeqNo = msgSeqNo == null ? null : msgSeqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.VERSION
     *
     * @return the value of JMF_RECV_MSG.VERSION
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.VERSION
     *
     * @param version the value for JMF_RECV_MSG.VERSION
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.TASK_NAME
     *
     * @return the value of JMF_RECV_MSG.TASK_NAME
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.TASK_NAME
     *
     * @param taskName the value for JMF_RECV_MSG.TASK_NAME
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.SYS_NAME
     *
     * @return the value of JMF_RECV_MSG.SYS_NAME
     * @mbg.generated
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.SYS_NAME
     *
     * @param sysName the value for JMF_RECV_MSG.SYS_NAME
     * @mbg.generated
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.MESSAGE_ID
     *
     * @return the value of JMF_RECV_MSG.MESSAGE_ID
     * @mbg.generated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.MESSAGE_ID
     *
     * @param messageId the value for JMF_RECV_MSG.MESSAGE_ID
     * @mbg.generated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.FILE_NAME
     *
     * @return the value of JMF_RECV_MSG.FILE_NAME
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.FILE_NAME
     *
     * @param fileName the value for JMF_RECV_MSG.FILE_NAME
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.MESSAGE_TYPE
     *
     * @return the value of JMF_RECV_MSG.MESSAGE_TYPE
     * @mbg.generated
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.MESSAGE_TYPE
     *
     * @param messageType the value for JMF_RECV_MSG.MESSAGE_TYPE
     * @mbg.generated
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.SENDER_ID
     *
     * @return the value of JMF_RECV_MSG.SENDER_ID
     * @mbg.generated
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.SENDER_ID
     *
     * @param senderId the value for JMF_RECV_MSG.SENDER_ID
     * @mbg.generated
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId == null ? null : senderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.RECEIVER_ID
     *
     * @return the value of JMF_RECV_MSG.RECEIVER_ID
     * @mbg.generated
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.RECEIVER_ID
     *
     * @param receiverId the value for JMF_RECV_MSG.RECEIVER_ID
     * @mbg.generated
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.SEND_TIME
     *
     * @return the value of JMF_RECV_MSG.SEND_TIME
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.SEND_TIME
     *
     * @param sendTime the value for JMF_RECV_MSG.SEND_TIME
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.STATUS
     *
     * @return the value of JMF_RECV_MSG.STATUS
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.STATUS
     *
     * @param status the value for JMF_RECV_MSG.STATUS
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.EXCEPTION_TYPE
     *
     * @return the value of JMF_RECV_MSG.EXCEPTION_TYPE
     * @mbg.generated
     */
    public String getExceptionType() {
        return exceptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.EXCEPTION_TYPE
     *
     * @param exceptionType the value for JMF_RECV_MSG.EXCEPTION_TYPE
     * @mbg.generated
     */
    public void setExceptionType(String exceptionType) {
        this.exceptionType = exceptionType == null ? null : exceptionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.ID_NAME1
     *
     * @return the value of JMF_RECV_MSG.ID_NAME1
     * @mbg.generated
     */
    public String getIdName1() {
        return idName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.ID_NAME1
     *
     * @param idName1 the value for JMF_RECV_MSG.ID_NAME1
     * @mbg.generated
     */
    public void setIdName1(String idName1) {
        this.idName1 = idName1 == null ? null : idName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.ID1
     *
     * @return the value of JMF_RECV_MSG.ID1
     * @mbg.generated
     */
    public String getId1() {
        return id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.ID1
     *
     * @param id1 the value for JMF_RECV_MSG.ID1
     * @mbg.generated
     */
    public void setId1(String id1) {
        this.id1 = id1 == null ? null : id1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.ID_NAME2
     *
     * @return the value of JMF_RECV_MSG.ID_NAME2
     * @mbg.generated
     */
    public String getIdName2() {
        return idName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.ID_NAME2
     *
     * @param idName2 the value for JMF_RECV_MSG.ID_NAME2
     * @mbg.generated
     */
    public void setIdName2(String idName2) {
        this.idName2 = idName2 == null ? null : idName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.ID2
     *
     * @return the value of JMF_RECV_MSG.ID2
     * @mbg.generated
     */
    public String getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.ID2
     *
     * @param id2 the value for JMF_RECV_MSG.ID2
     * @mbg.generated
     */
    public void setId2(String id2) {
        this.id2 = id2 == null ? null : id2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.ID_NAME3
     *
     * @return the value of JMF_RECV_MSG.ID_NAME3
     * @mbg.generated
     */
    public String getIdName3() {
        return idName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.ID_NAME3
     *
     * @param idName3 the value for JMF_RECV_MSG.ID_NAME3
     * @mbg.generated
     */
    public void setIdName3(String idName3) {
        this.idName3 = idName3 == null ? null : idName3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.ID3
     *
     * @return the value of JMF_RECV_MSG.ID3
     * @mbg.generated
     */
    public String getId3() {
        return id3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.ID3
     *
     * @param id3 the value for JMF_RECV_MSG.ID3
     * @mbg.generated
     */
    public void setId3(String id3) {
        this.id3 = id3 == null ? null : id3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.INFO_NAME1
     *
     * @return the value of JMF_RECV_MSG.INFO_NAME1
     * @mbg.generated
     */
    public String getInfoName1() {
        return infoName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.INFO_NAME1
     *
     * @param infoName1 the value for JMF_RECV_MSG.INFO_NAME1
     * @mbg.generated
     */
    public void setInfoName1(String infoName1) {
        this.infoName1 = infoName1 == null ? null : infoName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.INFO1
     *
     * @return the value of JMF_RECV_MSG.INFO1
     * @mbg.generated
     */
    public String getInfo1() {
        return info1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.INFO1
     *
     * @param info1 the value for JMF_RECV_MSG.INFO1
     * @mbg.generated
     */
    public void setInfo1(String info1) {
        this.info1 = info1 == null ? null : info1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.INFO_NAME2
     *
     * @return the value of JMF_RECV_MSG.INFO_NAME2
     * @mbg.generated
     */
    public String getInfoName2() {
        return infoName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.INFO_NAME2
     *
     * @param infoName2 the value for JMF_RECV_MSG.INFO_NAME2
     * @mbg.generated
     */
    public void setInfoName2(String infoName2) {
        this.infoName2 = infoName2 == null ? null : infoName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.INFO2
     *
     * @return the value of JMF_RECV_MSG.INFO2
     * @mbg.generated
     */
    public String getInfo2() {
        return info2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.INFO2
     *
     * @param info2 the value for JMF_RECV_MSG.INFO2
     * @mbg.generated
     */
    public void setInfo2(String info2) {
        this.info2 = info2 == null ? null : info2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.INFO_NAME3
     *
     * @return the value of JMF_RECV_MSG.INFO_NAME3
     * @mbg.generated
     */
    public String getInfoName3() {
        return infoName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.INFO_NAME3
     *
     * @param infoName3 the value for JMF_RECV_MSG.INFO_NAME3
     * @mbg.generated
     */
    public void setInfoName3(String infoName3) {
        this.infoName3 = infoName3 == null ? null : infoName3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.INFO3
     *
     * @return the value of JMF_RECV_MSG.INFO3
     * @mbg.generated
     */
    public String getInfo3() {
        return info3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.INFO3
     *
     * @param info3 the value for JMF_RECV_MSG.INFO3
     * @mbg.generated
     */
    public void setInfo3(String info3) {
        this.info3 = info3 == null ? null : info3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.INFO_STATUS
     *
     * @return the value of JMF_RECV_MSG.INFO_STATUS
     * @mbg.generated
     */
    public String getInfoStatus() {
        return infoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.INFO_STATUS
     *
     * @param infoStatus the value for JMF_RECV_MSG.INFO_STATUS
     * @mbg.generated
     */
    public void setInfoStatus(String infoStatus) {
        this.infoStatus = infoStatus == null ? null : infoStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.FILE_PATH
     *
     * @return the value of JMF_RECV_MSG.FILE_PATH
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.FILE_PATH
     *
     * @param filePath the value for JMF_RECV_MSG.FILE_PATH
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.ADD_TIME
     *
     * @return the value of JMF_RECV_MSG.ADD_TIME
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.ADD_TIME
     *
     * @param addTime the value for JMF_RECV_MSG.ADD_TIME
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.NOTES
     *
     * @return the value of JMF_RECV_MSG.NOTES
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.NOTES
     *
     * @param notes the value for JMF_RECV_MSG.NOTES
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.CREATETIME
     *
     * @return the value of JMF_RECV_MSG.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.CREATETIME
     *
     * @param createtime the value for JMF_RECV_MSG.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_RECV_MSG.UPDATETIME
     *
     * @return the value of JMF_RECV_MSG.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_RECV_MSG.UPDATETIME
     *
     * @param updatetime the value for JMF_RECV_MSG.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_RECV_MSG
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgSeqNo=").append(msgSeqNo);
        sb.append(", version=").append(version);
        sb.append(", taskName=").append(taskName);
        sb.append(", sysName=").append(sysName);
        sb.append(", messageId=").append(messageId);
        sb.append(", fileName=").append(fileName);
        sb.append(", messageType=").append(messageType);
        sb.append(", senderId=").append(senderId);
        sb.append(", receiverId=").append(receiverId);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", status=").append(status);
        sb.append(", exceptionType=").append(exceptionType);
        sb.append(", idName1=").append(idName1);
        sb.append(", id1=").append(id1);
        sb.append(", idName2=").append(idName2);
        sb.append(", id2=").append(id2);
        sb.append(", idName3=").append(idName3);
        sb.append(", id3=").append(id3);
        sb.append(", infoName1=").append(infoName1);
        sb.append(", info1=").append(info1);
        sb.append(", infoName2=").append(infoName2);
        sb.append(", info2=").append(info2);
        sb.append(", infoName3=").append(infoName3);
        sb.append(", info3=").append(info3);
        sb.append(", infoStatus=").append(infoStatus);
        sb.append(", filePath=").append(filePath);
        sb.append(", addTime=").append(addTime);
        sb.append(", notes=").append(notes);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}