package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfTaskConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.TASK_CONFIG_ID
     *
     * @mbg.generated
     */
    private String taskConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.TASK_NAME
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.AVG_COUNT
     *
     * @mbg.generated
     */
    private Integer avgCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.IS_SIGNATURE
     *
     * @mbg.generated
     */
    private String isSignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.SIGNATURE_UPDATE
     *
     * @mbg.generated
     */
    private String signatureUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.IS_ENCRYPT
     *
     * @mbg.generated
     */
    private String isEncrypt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.ENCRYPT_UPDATE
     *
     * @mbg.generated
     */
    private String encryptUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.IS_COMPRESS
     *
     * @mbg.generated
     */
    private String isCompress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.COMPRESS_UPDATE
     *
     * @mbg.generated
     */
    private String compressUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.IS_LANDING
     *
     * @mbg.generated
     */
    private String isLanding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.IS_VALIDATE
     *
     * @mbg.generated
     */
    private String isValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.VALIDATE_UPDATE
     *
     * @mbg.generated
     */
    private String validateUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.LANDING_UPDATE
     *
     * @mbg.generated
     */
    private String landingUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.SEND_MODE
     *
     * @mbg.generated
     */
    private String sendMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.MSG_LAND_PATH
     *
     * @mbg.generated
     */
    private String msgLandPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.CERT_SEQ_NO
     *
     * @mbg.generated
     */
    private String certSeqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.ENCRYPT_CONFIG_ID
     *
     * @mbg.generated
     */
    private String encryptConfigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.CRYPT_KEY_NO
     *
     * @mbg.generated
     */
    private Short cryptKeyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.CIPHER_KEY_NO
     *
     * @mbg.generated
     */
    private Short cipherKeyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.CMS_SIGN_ATTRIBUTE
     *
     * @mbg.generated
     */
    private String cmsSignAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.SIGN_ATTRIBUTE
     *
     * @mbg.generated
     */
    private Short signAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.XML_SIGN_ATTRIBUTE
     *
     * @mbg.generated
     */
    private String xmlSignAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.XML_HEAD_DIGEST_ATTRIBUTE
     *
     * @mbg.generated
     */
    private String xmlHeadDigestAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.PROVIDER_NAME
     *
     * @mbg.generated
     */
    private String providerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.IS_CLOSEMQCONN
     *
     * @mbg.generated
     */
    private String isClosemqconn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CONFIG.CLOSEMQCONN_UPDATE
     *
     * @mbg.generated
     */
    private String closemqconnUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_TASK_CONFIG
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.TASK_CONFIG_ID
     *
     * @return the value of JMF_TASK_CONFIG.TASK_CONFIG_ID
     * @mbg.generated
     */
    public String getTaskConfigId() {
        return taskConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.TASK_CONFIG_ID
     *
     * @param taskConfigId the value for JMF_TASK_CONFIG.TASK_CONFIG_ID
     * @mbg.generated
     */
    public void setTaskConfigId(String taskConfigId) {
        this.taskConfigId = taskConfigId == null ? null : taskConfigId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.TASK_NAME
     *
     * @return the value of JMF_TASK_CONFIG.TASK_NAME
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.TASK_NAME
     *
     * @param taskName the value for JMF_TASK_CONFIG.TASK_NAME
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.AVG_COUNT
     *
     * @return the value of JMF_TASK_CONFIG.AVG_COUNT
     * @mbg.generated
     */
    public Integer getAvgCount() {
        return avgCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.AVG_COUNT
     *
     * @param avgCount the value for JMF_TASK_CONFIG.AVG_COUNT
     * @mbg.generated
     */
    public void setAvgCount(Integer avgCount) {
        this.avgCount = avgCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.IS_SIGNATURE
     *
     * @return the value of JMF_TASK_CONFIG.IS_SIGNATURE
     * @mbg.generated
     */
    public String getIsSignature() {
        return isSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.IS_SIGNATURE
     *
     * @param isSignature the value for JMF_TASK_CONFIG.IS_SIGNATURE
     * @mbg.generated
     */
    public void setIsSignature(String isSignature) {
        this.isSignature = isSignature == null ? null : isSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.SIGNATURE_UPDATE
     *
     * @return the value of JMF_TASK_CONFIG.SIGNATURE_UPDATE
     * @mbg.generated
     */
    public String getSignatureUpdate() {
        return signatureUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.SIGNATURE_UPDATE
     *
     * @param signatureUpdate the value for JMF_TASK_CONFIG.SIGNATURE_UPDATE
     * @mbg.generated
     */
    public void setSignatureUpdate(String signatureUpdate) {
        this.signatureUpdate = signatureUpdate == null ? null : signatureUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.IS_ENCRYPT
     *
     * @return the value of JMF_TASK_CONFIG.IS_ENCRYPT
     * @mbg.generated
     */
    public String getIsEncrypt() {
        return isEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.IS_ENCRYPT
     *
     * @param isEncrypt the value for JMF_TASK_CONFIG.IS_ENCRYPT
     * @mbg.generated
     */
    public void setIsEncrypt(String isEncrypt) {
        this.isEncrypt = isEncrypt == null ? null : isEncrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.ENCRYPT_UPDATE
     *
     * @return the value of JMF_TASK_CONFIG.ENCRYPT_UPDATE
     * @mbg.generated
     */
    public String getEncryptUpdate() {
        return encryptUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.ENCRYPT_UPDATE
     *
     * @param encryptUpdate the value for JMF_TASK_CONFIG.ENCRYPT_UPDATE
     * @mbg.generated
     */
    public void setEncryptUpdate(String encryptUpdate) {
        this.encryptUpdate = encryptUpdate == null ? null : encryptUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.IS_COMPRESS
     *
     * @return the value of JMF_TASK_CONFIG.IS_COMPRESS
     * @mbg.generated
     */
    public String getIsCompress() {
        return isCompress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.IS_COMPRESS
     *
     * @param isCompress the value for JMF_TASK_CONFIG.IS_COMPRESS
     * @mbg.generated
     */
    public void setIsCompress(String isCompress) {
        this.isCompress = isCompress == null ? null : isCompress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.COMPRESS_UPDATE
     *
     * @return the value of JMF_TASK_CONFIG.COMPRESS_UPDATE
     * @mbg.generated
     */
    public String getCompressUpdate() {
        return compressUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.COMPRESS_UPDATE
     *
     * @param compressUpdate the value for JMF_TASK_CONFIG.COMPRESS_UPDATE
     * @mbg.generated
     */
    public void setCompressUpdate(String compressUpdate) {
        this.compressUpdate = compressUpdate == null ? null : compressUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.IS_LANDING
     *
     * @return the value of JMF_TASK_CONFIG.IS_LANDING
     * @mbg.generated
     */
    public String getIsLanding() {
        return isLanding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.IS_LANDING
     *
     * @param isLanding the value for JMF_TASK_CONFIG.IS_LANDING
     * @mbg.generated
     */
    public void setIsLanding(String isLanding) {
        this.isLanding = isLanding == null ? null : isLanding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.IS_VALIDATE
     *
     * @return the value of JMF_TASK_CONFIG.IS_VALIDATE
     * @mbg.generated
     */
    public String getIsValidate() {
        return isValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.IS_VALIDATE
     *
     * @param isValidate the value for JMF_TASK_CONFIG.IS_VALIDATE
     * @mbg.generated
     */
    public void setIsValidate(String isValidate) {
        this.isValidate = isValidate == null ? null : isValidate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.VALIDATE_UPDATE
     *
     * @return the value of JMF_TASK_CONFIG.VALIDATE_UPDATE
     * @mbg.generated
     */
    public String getValidateUpdate() {
        return validateUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.VALIDATE_UPDATE
     *
     * @param validateUpdate the value for JMF_TASK_CONFIG.VALIDATE_UPDATE
     * @mbg.generated
     */
    public void setValidateUpdate(String validateUpdate) {
        this.validateUpdate = validateUpdate == null ? null : validateUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.LANDING_UPDATE
     *
     * @return the value of JMF_TASK_CONFIG.LANDING_UPDATE
     * @mbg.generated
     */
    public String getLandingUpdate() {
        return landingUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.LANDING_UPDATE
     *
     * @param landingUpdate the value for JMF_TASK_CONFIG.LANDING_UPDATE
     * @mbg.generated
     */
    public void setLandingUpdate(String landingUpdate) {
        this.landingUpdate = landingUpdate == null ? null : landingUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.SEND_MODE
     *
     * @return the value of JMF_TASK_CONFIG.SEND_MODE
     * @mbg.generated
     */
    public String getSendMode() {
        return sendMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.SEND_MODE
     *
     * @param sendMode the value for JMF_TASK_CONFIG.SEND_MODE
     * @mbg.generated
     */
    public void setSendMode(String sendMode) {
        this.sendMode = sendMode == null ? null : sendMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.MSG_LAND_PATH
     *
     * @return the value of JMF_TASK_CONFIG.MSG_LAND_PATH
     * @mbg.generated
     */
    public String getMsgLandPath() {
        return msgLandPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.MSG_LAND_PATH
     *
     * @param msgLandPath the value for JMF_TASK_CONFIG.MSG_LAND_PATH
     * @mbg.generated
     */
    public void setMsgLandPath(String msgLandPath) {
        this.msgLandPath = msgLandPath == null ? null : msgLandPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.CERT_SEQ_NO
     *
     * @return the value of JMF_TASK_CONFIG.CERT_SEQ_NO
     * @mbg.generated
     */
    public String getCertSeqNo() {
        return certSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.CERT_SEQ_NO
     *
     * @param certSeqNo the value for JMF_TASK_CONFIG.CERT_SEQ_NO
     * @mbg.generated
     */
    public void setCertSeqNo(String certSeqNo) {
        this.certSeqNo = certSeqNo == null ? null : certSeqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.ENCRYPT_CONFIG_ID
     *
     * @return the value of JMF_TASK_CONFIG.ENCRYPT_CONFIG_ID
     * @mbg.generated
     */
    public String getEncryptConfigId() {
        return encryptConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.ENCRYPT_CONFIG_ID
     *
     * @param encryptConfigId the value for JMF_TASK_CONFIG.ENCRYPT_CONFIG_ID
     * @mbg.generated
     */
    public void setEncryptConfigId(String encryptConfigId) {
        this.encryptConfigId = encryptConfigId == null ? null : encryptConfigId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.CREATETIME
     *
     * @return the value of JMF_TASK_CONFIG.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.CREATETIME
     *
     * @param createtime the value for JMF_TASK_CONFIG.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.UPDATETIME
     *
     * @return the value of JMF_TASK_CONFIG.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.UPDATETIME
     *
     * @param updatetime the value for JMF_TASK_CONFIG.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.CRYPT_KEY_NO
     *
     * @return the value of JMF_TASK_CONFIG.CRYPT_KEY_NO
     * @mbg.generated
     */
    public Short getCryptKeyNo() {
        return cryptKeyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.CRYPT_KEY_NO
     *
     * @param cryptKeyNo the value for JMF_TASK_CONFIG.CRYPT_KEY_NO
     * @mbg.generated
     */
    public void setCryptKeyNo(Short cryptKeyNo) {
        this.cryptKeyNo = cryptKeyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.CIPHER_KEY_NO
     *
     * @return the value of JMF_TASK_CONFIG.CIPHER_KEY_NO
     * @mbg.generated
     */
    public Short getCipherKeyNo() {
        return cipherKeyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.CIPHER_KEY_NO
     *
     * @param cipherKeyNo the value for JMF_TASK_CONFIG.CIPHER_KEY_NO
     * @mbg.generated
     */
    public void setCipherKeyNo(Short cipherKeyNo) {
        this.cipherKeyNo = cipherKeyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.CMS_SIGN_ATTRIBUTE
     *
     * @return the value of JMF_TASK_CONFIG.CMS_SIGN_ATTRIBUTE
     * @mbg.generated
     */
    public String getCmsSignAttribute() {
        return cmsSignAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.CMS_SIGN_ATTRIBUTE
     *
     * @param cmsSignAttribute the value for JMF_TASK_CONFIG.CMS_SIGN_ATTRIBUTE
     * @mbg.generated
     */
    public void setCmsSignAttribute(String cmsSignAttribute) {
        this.cmsSignAttribute = cmsSignAttribute == null ? null : cmsSignAttribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.SIGN_ATTRIBUTE
     *
     * @return the value of JMF_TASK_CONFIG.SIGN_ATTRIBUTE
     * @mbg.generated
     */
    public Short getSignAttribute() {
        return signAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.SIGN_ATTRIBUTE
     *
     * @param signAttribute the value for JMF_TASK_CONFIG.SIGN_ATTRIBUTE
     * @mbg.generated
     */
    public void setSignAttribute(Short signAttribute) {
        this.signAttribute = signAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.XML_SIGN_ATTRIBUTE
     *
     * @return the value of JMF_TASK_CONFIG.XML_SIGN_ATTRIBUTE
     * @mbg.generated
     */
    public String getXmlSignAttribute() {
        return xmlSignAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.XML_SIGN_ATTRIBUTE
     *
     * @param xmlSignAttribute the value for JMF_TASK_CONFIG.XML_SIGN_ATTRIBUTE
     * @mbg.generated
     */
    public void setXmlSignAttribute(String xmlSignAttribute) {
        this.xmlSignAttribute = xmlSignAttribute == null ? null : xmlSignAttribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.XML_HEAD_DIGEST_ATTRIBUTE
     *
     * @return the value of JMF_TASK_CONFIG.XML_HEAD_DIGEST_ATTRIBUTE
     * @mbg.generated
     */
    public String getXmlHeadDigestAttribute() {
        return xmlHeadDigestAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.XML_HEAD_DIGEST_ATTRIBUTE
     *
     * @param xmlHeadDigestAttribute the value for JMF_TASK_CONFIG.XML_HEAD_DIGEST_ATTRIBUTE
     * @mbg.generated
     */
    public void setXmlHeadDigestAttribute(String xmlHeadDigestAttribute) {
        this.xmlHeadDigestAttribute = xmlHeadDigestAttribute == null ? null : xmlHeadDigestAttribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.PROVIDER_NAME
     *
     * @return the value of JMF_TASK_CONFIG.PROVIDER_NAME
     * @mbg.generated
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.PROVIDER_NAME
     *
     * @param providerName the value for JMF_TASK_CONFIG.PROVIDER_NAME
     * @mbg.generated
     */
    public void setProviderName(String providerName) {
        this.providerName = providerName == null ? null : providerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.IS_CLOSEMQCONN
     *
     * @return the value of JMF_TASK_CONFIG.IS_CLOSEMQCONN
     * @mbg.generated
     */
    public String getIsClosemqconn() {
        return isClosemqconn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.IS_CLOSEMQCONN
     *
     * @param isClosemqconn the value for JMF_TASK_CONFIG.IS_CLOSEMQCONN
     * @mbg.generated
     */
    public void setIsClosemqconn(String isClosemqconn) {
        this.isClosemqconn = isClosemqconn == null ? null : isClosemqconn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CONFIG.CLOSEMQCONN_UPDATE
     *
     * @return the value of JMF_TASK_CONFIG.CLOSEMQCONN_UPDATE
     * @mbg.generated
     */
    public String getClosemqconnUpdate() {
        return closemqconnUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CONFIG.CLOSEMQCONN_UPDATE
     *
     * @param closemqconnUpdate the value for JMF_TASK_CONFIG.CLOSEMQCONN_UPDATE
     * @mbg.generated
     */
    public void setClosemqconnUpdate(String closemqconnUpdate) {
        this.closemqconnUpdate = closemqconnUpdate == null ? null : closemqconnUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CONFIG
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskConfigId=").append(taskConfigId);
        sb.append(", taskName=").append(taskName);
        sb.append(", avgCount=").append(avgCount);
        sb.append(", isSignature=").append(isSignature);
        sb.append(", signatureUpdate=").append(signatureUpdate);
        sb.append(", isEncrypt=").append(isEncrypt);
        sb.append(", encryptUpdate=").append(encryptUpdate);
        sb.append(", isCompress=").append(isCompress);
        sb.append(", compressUpdate=").append(compressUpdate);
        sb.append(", isLanding=").append(isLanding);
        sb.append(", isValidate=").append(isValidate);
        sb.append(", validateUpdate=").append(validateUpdate);
        sb.append(", landingUpdate=").append(landingUpdate);
        sb.append(", sendMode=").append(sendMode);
        sb.append(", msgLandPath=").append(msgLandPath);
        sb.append(", certSeqNo=").append(certSeqNo);
        sb.append(", encryptConfigId=").append(encryptConfigId);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", cryptKeyNo=").append(cryptKeyNo);
        sb.append(", cipherKeyNo=").append(cipherKeyNo);
        sb.append(", cmsSignAttribute=").append(cmsSignAttribute);
        sb.append(", signAttribute=").append(signAttribute);
        sb.append(", xmlSignAttribute=").append(xmlSignAttribute);
        sb.append(", xmlHeadDigestAttribute=").append(xmlHeadDigestAttribute);
        sb.append(", providerName=").append(providerName);
        sb.append(", isClosemqconn=").append(isClosemqconn);
        sb.append(", closemqconnUpdate=").append(closemqconnUpdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}