package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfTaskList implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.TASK_ID
     *
     * @mbg.generated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.JVM_ID
     *
     * @mbg.generated
     */
    private String jvmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.APP_NAME
     *
     * @mbg.generated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.TASK_NAME
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.METHOD_NAME
     *
     * @mbg.generated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.TRIGGER_TYPE
     *
     * @mbg.generated
     */
    private String triggerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.TRIGGER_PARA
     *
     * @mbg.generated
     */
    private String triggerPara;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.METHOD_ARGUMENTS
     *
     * @mbg.generated
     */
    private String methodArguments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.OPREATION_TIME
     *
     * @mbg.generated
     */
    private Date opreationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.MSG_TYPE
     *
     * @mbg.generated
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.GROUP_FLAG
     *
     * @mbg.generated
     */
    private String groupFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.GROUPNO
     *
     * @mbg.generated
     */
    private String groupno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.GROUPNUM
     *
     * @mbg.generated
     */
    private String groupnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_LIST.NOTE
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_TASK_LIST
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.TASK_ID
     *
     * @return the value of JMF_TASK_LIST.TASK_ID
     * @mbg.generated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.TASK_ID
     *
     * @param taskId the value for JMF_TASK_LIST.TASK_ID
     * @mbg.generated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.JVM_ID
     *
     * @return the value of JMF_TASK_LIST.JVM_ID
     * @mbg.generated
     */
    public String getJvmId() {
        return jvmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.JVM_ID
     *
     * @param jvmId the value for JMF_TASK_LIST.JVM_ID
     * @mbg.generated
     */
    public void setJvmId(String jvmId) {
        this.jvmId = jvmId == null ? null : jvmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.APP_NAME
     *
     * @return the value of JMF_TASK_LIST.APP_NAME
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.APP_NAME
     *
     * @param appName the value for JMF_TASK_LIST.APP_NAME
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.TASK_NAME
     *
     * @return the value of JMF_TASK_LIST.TASK_NAME
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.TASK_NAME
     *
     * @param taskName the value for JMF_TASK_LIST.TASK_NAME
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.METHOD_NAME
     *
     * @return the value of JMF_TASK_LIST.METHOD_NAME
     * @mbg.generated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.METHOD_NAME
     *
     * @param methodName the value for JMF_TASK_LIST.METHOD_NAME
     * @mbg.generated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.TRIGGER_TYPE
     *
     * @return the value of JMF_TASK_LIST.TRIGGER_TYPE
     * @mbg.generated
     */
    public String getTriggerType() {
        return triggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.TRIGGER_TYPE
     *
     * @param triggerType the value for JMF_TASK_LIST.TRIGGER_TYPE
     * @mbg.generated
     */
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType == null ? null : triggerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.TRIGGER_PARA
     *
     * @return the value of JMF_TASK_LIST.TRIGGER_PARA
     * @mbg.generated
     */
    public String getTriggerPara() {
        return triggerPara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.TRIGGER_PARA
     *
     * @param triggerPara the value for JMF_TASK_LIST.TRIGGER_PARA
     * @mbg.generated
     */
    public void setTriggerPara(String triggerPara) {
        this.triggerPara = triggerPara == null ? null : triggerPara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.METHOD_ARGUMENTS
     *
     * @return the value of JMF_TASK_LIST.METHOD_ARGUMENTS
     * @mbg.generated
     */
    public String getMethodArguments() {
        return methodArguments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.METHOD_ARGUMENTS
     *
     * @param methodArguments the value for JMF_TASK_LIST.METHOD_ARGUMENTS
     * @mbg.generated
     */
    public void setMethodArguments(String methodArguments) {
        this.methodArguments = methodArguments == null ? null : methodArguments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.OPREATION_TIME
     *
     * @return the value of JMF_TASK_LIST.OPREATION_TIME
     * @mbg.generated
     */
    public Date getOpreationTime() {
        return opreationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.OPREATION_TIME
     *
     * @param opreationTime the value for JMF_TASK_LIST.OPREATION_TIME
     * @mbg.generated
     */
    public void setOpreationTime(Date opreationTime) {
        this.opreationTime = opreationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.MSG_TYPE
     *
     * @return the value of JMF_TASK_LIST.MSG_TYPE
     * @mbg.generated
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.MSG_TYPE
     *
     * @param msgType the value for JMF_TASK_LIST.MSG_TYPE
     * @mbg.generated
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType == null ? null : msgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.GROUP_FLAG
     *
     * @return the value of JMF_TASK_LIST.GROUP_FLAG
     * @mbg.generated
     */
    public String getGroupFlag() {
        return groupFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.GROUP_FLAG
     *
     * @param groupFlag the value for JMF_TASK_LIST.GROUP_FLAG
     * @mbg.generated
     */
    public void setGroupFlag(String groupFlag) {
        this.groupFlag = groupFlag == null ? null : groupFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.STATUS
     *
     * @return the value of JMF_TASK_LIST.STATUS
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.STATUS
     *
     * @param status the value for JMF_TASK_LIST.STATUS
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.GROUPNO
     *
     * @return the value of JMF_TASK_LIST.GROUPNO
     * @mbg.generated
     */
    public String getGroupno() {
        return groupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.GROUPNO
     *
     * @param groupno the value for JMF_TASK_LIST.GROUPNO
     * @mbg.generated
     */
    public void setGroupno(String groupno) {
        this.groupno = groupno == null ? null : groupno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.GROUPNUM
     *
     * @return the value of JMF_TASK_LIST.GROUPNUM
     * @mbg.generated
     */
    public String getGroupnum() {
        return groupnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.GROUPNUM
     *
     * @param groupnum the value for JMF_TASK_LIST.GROUPNUM
     * @mbg.generated
     */
    public void setGroupnum(String groupnum) {
        this.groupnum = groupnum == null ? null : groupnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.CREATETIME
     *
     * @return the value of JMF_TASK_LIST.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.CREATETIME
     *
     * @param createtime the value for JMF_TASK_LIST.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.UPDATETIME
     *
     * @return the value of JMF_TASK_LIST.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.UPDATETIME
     *
     * @param updatetime the value for JMF_TASK_LIST.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_LIST.NOTE
     *
     * @return the value of JMF_TASK_LIST.NOTE
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_LIST.NOTE
     *
     * @param note the value for JMF_TASK_LIST.NOTE
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_LIST
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", taskId=").append(taskId);
        sb.append(", jvmId=").append(jvmId);
        sb.append(", appName=").append(appName);
        sb.append(", taskName=").append(taskName);
        sb.append(", methodName=").append(methodName);
        sb.append(", triggerType=").append(triggerType);
        sb.append(", triggerPara=").append(triggerPara);
        sb.append(", methodArguments=").append(methodArguments);
        sb.append(", opreationTime=").append(opreationTime);
        sb.append(", msgType=").append(msgType);
        sb.append(", groupFlag=").append(groupFlag);
        sb.append(", status=").append(status);
        sb.append(", groupno=").append(groupno);
        sb.append(", groupnum=").append(groupnum);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}