package com.jmf.impl.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class JmfTest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TEST.SEQ_ID
     *
     * @mbg.generated
     */
    private BigDecimal seqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TEST.FIRST_NAME
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TEST.NAME
     *
     * @mbg.generated
     */
    private byte[] name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_TEST
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TEST.SEQ_ID
     *
     * @return the value of JMF_TEST.SEQ_ID
     * @mbg.generated
     */
    public BigDecimal getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TEST.SEQ_ID
     *
     * @param seqId the value for JMF_TEST.SEQ_ID
     * @mbg.generated
     */
    public void setSeqId(BigDecimal seqId) {
        this.seqId = seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TEST.FIRST_NAME
     *
     * @return the value of JMF_TEST.FIRST_NAME
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TEST.FIRST_NAME
     *
     * @param firstName the value for JMF_TEST.FIRST_NAME
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TEST.NAME
     *
     * @return the value of JMF_TEST.NAME
     * @mbg.generated
     */
    public byte[] getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TEST.NAME
     *
     * @param name the value for JMF_TEST.NAME
     * @mbg.generated
     */
    public void setName(byte[] name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TEST
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", seqId=").append(seqId);
        sb.append(", firstName=").append(firstName);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}