package com.jmf.impl.entity;

import java.io.Serializable;
import java.util.Date;

public class JmfTaskCertRef implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CERT_REF.RELATION_ID
     *
     * @mbg.generated
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CERT_REF.TASK_NAME
     *
     * @mbg.generated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CERT_REF.CONFIG_ID
     *
     * @mbg.generated
     */
    private String configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CERT_REF.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CERT_REF.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JMF_TASK_CERT_REF.UPDATETIME
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JMF_TASK_CERT_REF
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CERT_REF.RELATION_ID
     *
     * @return the value of JMF_TASK_CERT_REF.RELATION_ID
     * @mbg.generated
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CERT_REF.RELATION_ID
     *
     * @param relationId the value for JMF_TASK_CERT_REF.RELATION_ID
     * @mbg.generated
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId == null ? null : relationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CERT_REF.TASK_NAME
     *
     * @return the value of JMF_TASK_CERT_REF.TASK_NAME
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CERT_REF.TASK_NAME
     *
     * @param taskName the value for JMF_TASK_CERT_REF.TASK_NAME
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CERT_REF.CONFIG_ID
     *
     * @return the value of JMF_TASK_CERT_REF.CONFIG_ID
     * @mbg.generated
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CERT_REF.CONFIG_ID
     *
     * @param configId the value for JMF_TASK_CERT_REF.CONFIG_ID
     * @mbg.generated
     */
    public void setConfigId(String configId) {
        this.configId = configId == null ? null : configId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CERT_REF.DESCRIPTION
     *
     * @return the value of JMF_TASK_CERT_REF.DESCRIPTION
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CERT_REF.DESCRIPTION
     *
     * @param description the value for JMF_TASK_CERT_REF.DESCRIPTION
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CERT_REF.CREATETIME
     *
     * @return the value of JMF_TASK_CERT_REF.CREATETIME
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CERT_REF.CREATETIME
     *
     * @param createtime the value for JMF_TASK_CERT_REF.CREATETIME
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JMF_TASK_CERT_REF.UPDATETIME
     *
     * @return the value of JMF_TASK_CERT_REF.UPDATETIME
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JMF_TASK_CERT_REF.UPDATETIME
     *
     * @param updatetime the value for JMF_TASK_CERT_REF.UPDATETIME
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JMF_TASK_CERT_REF
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", relationId=").append(relationId);
        sb.append(", taskName=").append(taskName);
        sb.append(", configId=").append(configId);
        sb.append(", description=").append(description);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}